version: "3.8"
services: 
    nginx: 
        image: nginx:latest
        restart: always
        # 因为用的host模式所以可以不用映射端口号
        # ports: 
        #    - "80:80"
        #    - "443:443"
        volumes: 
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/certs:/etc/nginx/certs
        network_mode: host
        container_name: nginx_usa

    mysql: 
        image: mysql:latest
        command:
            --character-set-server=utf8
        restart: always
        # ports:
        #    - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        network_mode: host
        container_name: mysql

    v2ray: 
        restart: always
        depends_on:
            - nginx
        image: v2fly/v2fly-core
        volumes: 
            - ./v2fly/config.json:/etc/v2ray/config.json
            # - ./nginx/certs:/etc/v2ray/certs
        network_mode: host
        container_name: v2ray
  